DROP TABLE Users CASCADE;
DROP TABLE UsersInfo CASCADE;


DROP TABLE Books CASCADE;
DROP TABLE OwnedBooks CASCADE;
DROP TABLE SwapRequests CASCADE;
DROP TABLE AcceptedSwaps CASCADE;
DROP TABLE RejectedSwaps CASCADE;
DROP TABLE CompletedSwaps CASCADE;